[package]
name = "egb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.6.0"
lazy_static = "1.5.0"
tinytga = "0.5.0"
